/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CashRegisterSession {
  'id' : bigint,
  'closeTime' : [] | [Time],
  'isOpen' : boolean,
  'finalBalanceCents' : [] | [bigint],
  'initialFloatCents' : bigint,
  'openTime' : Time,
}
export interface CloseRegisterRequest {
  'sessionId' : bigint,
  'finalBalanceCents' : bigint,
}
export interface ClosingRecord {
  'id' : bigint,
  'closeTime' : Time,
  'sessionId' : bigint,
  'finalBalanceCents' : bigint,
}
export interface CreateCustomerRequest {
  'id' : string,
  'name' : string,
  'phone' : string,
}
export interface Customer {
  'id' : string,
  'eligibleForRaffle' : boolean,
  'name' : string,
  'totalPurchasesCents' : bigint,
  'phone' : string,
}
export interface OpenRegisterRequest { 'initialFloatCents' : bigint }
export type PaymentMethod = { 'pix' : null } |
  { 'credito' : null } |
  { 'debito' : null } |
  { 'dinheiro' : null };
export interface Sale {
  'id' : bigint,
  'paymentMethod' : PaymentMethod,
  'date' : Time,
  'totalCents' : bigint,
  'changeCents' : bigint,
  'customerId' : [] | [string],
  'items' : Array<SaleItem>,
}
export interface SaleItem {
  'itemId' : string,
  'name' : string,
  'totalCents' : bigint,
  'quantity' : bigint,
  'priceCents' : bigint,
}
export type Time = bigint;
export interface UpdateCustomerRequest {
  'id' : string,
  'name' : string,
  'phone' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'closeRegister' : ActorMethod<[CloseRegisterRequest], undefined>,
  'createCustomer' : ActorMethod<[CreateCustomerRequest], Customer>,
  'deleteSale' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[string], Customer>,
  'getOpenRegisterSession' : ActorMethod<[], [] | [CashRegisterSession]>,
  'getSale' : ActorMethod<[bigint], [] | [Sale]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listClosingRecords' : ActorMethod<[], Array<ClosingRecord>>,
  'listCustomers' : ActorMethod<[], Array<Customer>>,
  'listRegisterSessions' : ActorMethod<[], Array<CashRegisterSession>>,
  'listSales' : ActorMethod<[], Array<Sale>>,
  'listSalesByCustomer' : ActorMethod<[string], Array<Sale>>,
  'openRegister' : ActorMethod<[OpenRegisterRequest], CashRegisterSession>,
  'recordSale' : ActorMethod<
    [[] | [string], Array<SaleItem>, PaymentMethod, bigint],
    Sale
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCustomer' : ActorMethod<[UpdateCustomerRequest], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];