/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CloseRegisterRequest = IDL.Record({
  'sessionId' : IDL.Nat,
  'finalBalanceCents' : IDL.Int,
});
export const CreateCustomerRequest = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const Customer = IDL.Record({
  'id' : IDL.Text,
  'eligibleForRaffle' : IDL.Bool,
  'name' : IDL.Text,
  'totalPurchasesCents' : IDL.Int,
  'phone' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'pix' : IDL.Null,
  'credito' : IDL.Null,
  'debito' : IDL.Null,
  'dinheiro' : IDL.Null,
});
export const SaleItem = IDL.Record({
  'itemId' : IDL.Text,
  'name' : IDL.Text,
  'totalCents' : IDL.Int,
  'quantity' : IDL.Nat,
  'priceCents' : IDL.Int,
});
export const SaleStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
});
export const Time = IDL.Int;
export const Sale = IDL.Record({
  'id' : IDL.Nat,
  'status' : SaleStatus,
  'paymentMethod' : PaymentMethod,
  'date' : Time,
  'totalCents' : IDL.Int,
  'changeCents' : IDL.Int,
  'customerId' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(SaleItem),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CashRegisterSession = IDL.Record({
  'id' : IDL.Nat,
  'closeTime' : IDL.Opt(Time),
  'isOpen' : IDL.Bool,
  'finalBalanceCents' : IDL.Opt(IDL.Int),
  'initialFloatCents' : IDL.Int,
  'openTime' : Time,
});
export const SaleEditLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Variant({ 'edit' : IDL.Null, 'cancel' : IDL.Null }),
  'saleId' : IDL.Nat,
  'editor' : IDL.Principal,
  'newValue' : Sale,
  'previousValue' : Sale,
  'timestamp' : Time,
});
export const ClosingRecord = IDL.Record({
  'id' : IDL.Nat,
  'closeTime' : Time,
  'sessionId' : IDL.Nat,
  'finalBalanceCents' : IDL.Int,
});
export const OpenRegisterRequest = IDL.Record({
  'initialFloatCents' : IDL.Int,
});
export const UpdateCustomerRequest = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelSaleToday' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'closeRegister' : IDL.Func([CloseRegisterRequest], [], []),
  'createCustomer' : IDL.Func([CreateCustomerRequest], [Customer], []),
  'deleteSale' : IDL.Func([IDL.Nat], [], []),
  'editSaleToday' : IDL.Func(
      [IDL.Nat, PaymentMethod, IDL.Vec(SaleItem)],
      [IDL.Bool],
      [],
    ),
  'getActiveSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [Customer], ['query']),
  'getOpenRegisterSession' : IDL.Func(
      [],
      [IDL.Opt(CashRegisterSession)],
      ['query'],
    ),
  'getSale' : IDL.Func([IDL.Nat], [IDL.Opt(Sale)], ['query']),
  'getSaleEditLogsByEditor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SaleEditLog)],
      ['query'],
    ),
  'getSaleEditLogsBySale' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SaleEditLog)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listClosingRecords' : IDL.Func([], [IDL.Vec(ClosingRecord)], ['query']),
  'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'listRegisterSessions' : IDL.Func(
      [],
      [IDL.Vec(CashRegisterSession)],
      ['query'],
    ),
  'listSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'listSalesByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Sale)], ['query']),
  'openRegister' : IDL.Func([OpenRegisterRequest], [CashRegisterSession], []),
  'recordSale' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Vec(SaleItem), PaymentMethod, IDL.Int],
      [Sale],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCustomer' : IDL.Func([UpdateCustomerRequest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CloseRegisterRequest = IDL.Record({
    'sessionId' : IDL.Nat,
    'finalBalanceCents' : IDL.Int,
  });
  const CreateCustomerRequest = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Customer = IDL.Record({
    'id' : IDL.Text,
    'eligibleForRaffle' : IDL.Bool,
    'name' : IDL.Text,
    'totalPurchasesCents' : IDL.Int,
    'phone' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'pix' : IDL.Null,
    'credito' : IDL.Null,
    'debito' : IDL.Null,
    'dinheiro' : IDL.Null,
  });
  const SaleItem = IDL.Record({
    'itemId' : IDL.Text,
    'name' : IDL.Text,
    'totalCents' : IDL.Int,
    'quantity' : IDL.Nat,
    'priceCents' : IDL.Int,
  });
  const SaleStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
  });
  const Time = IDL.Int;
  const Sale = IDL.Record({
    'id' : IDL.Nat,
    'status' : SaleStatus,
    'paymentMethod' : PaymentMethod,
    'date' : Time,
    'totalCents' : IDL.Int,
    'changeCents' : IDL.Int,
    'customerId' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(SaleItem),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CashRegisterSession = IDL.Record({
    'id' : IDL.Nat,
    'closeTime' : IDL.Opt(Time),
    'isOpen' : IDL.Bool,
    'finalBalanceCents' : IDL.Opt(IDL.Int),
    'initialFloatCents' : IDL.Int,
    'openTime' : Time,
  });
  const SaleEditLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Variant({ 'edit' : IDL.Null, 'cancel' : IDL.Null }),
    'saleId' : IDL.Nat,
    'editor' : IDL.Principal,
    'newValue' : Sale,
    'previousValue' : Sale,
    'timestamp' : Time,
  });
  const ClosingRecord = IDL.Record({
    'id' : IDL.Nat,
    'closeTime' : Time,
    'sessionId' : IDL.Nat,
    'finalBalanceCents' : IDL.Int,
  });
  const OpenRegisterRequest = IDL.Record({ 'initialFloatCents' : IDL.Int });
  const UpdateCustomerRequest = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelSaleToday' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'closeRegister' : IDL.Func([CloseRegisterRequest], [], []),
    'createCustomer' : IDL.Func([CreateCustomerRequest], [Customer], []),
    'deleteSale' : IDL.Func([IDL.Nat], [], []),
    'editSaleToday' : IDL.Func(
        [IDL.Nat, PaymentMethod, IDL.Vec(SaleItem)],
        [IDL.Bool],
        [],
      ),
    'getActiveSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [Customer], ['query']),
    'getOpenRegisterSession' : IDL.Func(
        [],
        [IDL.Opt(CashRegisterSession)],
        ['query'],
      ),
    'getSale' : IDL.Func([IDL.Nat], [IDL.Opt(Sale)], ['query']),
    'getSaleEditLogsByEditor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SaleEditLog)],
        ['query'],
      ),
    'getSaleEditLogsBySale' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SaleEditLog)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listClosingRecords' : IDL.Func([], [IDL.Vec(ClosingRecord)], ['query']),
    'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'listRegisterSessions' : IDL.Func(
        [],
        [IDL.Vec(CashRegisterSession)],
        ['query'],
      ),
    'listSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'listSalesByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Sale)], ['query']),
    'openRegister' : IDL.Func([OpenRegisterRequest], [CashRegisterSession], []),
    'recordSale' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Vec(SaleItem), PaymentMethod, IDL.Int],
        [Sale],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCustomer' : IDL.Func([UpdateCustomerRequest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };